use db;
select * from film_locations_in_san_francisco;
select Title,Director,Writer,`Release Year` from film_locations_in_san_francisco;
SELECT Title,`Release Year`,Locations,Writer FROM film_locations_in_san_francisco WHERE `Release Year`>1920;
select Locations,`Fun Facts` from film_locations_in_san_francisco;
select Title,`Production Company`,Locations,`Release Year` from film_locations_in_san_francisco where Writer <> "James Cameron";
select count(*) from film_locations_in_san_francisco;
select count(Locations) from film_locations_in_san_francisco where Writer="Anita Loos";
select count(Locations) from film_locations_in_san_francisco where Director="Charles Chaplin";
select count(Title) from film_locations_in_san_francisco where Locations="City Hall";
select count(`Release Year`) from film_locations_in_san_francisco where `Release Year`>"1950";
select distinct(Title) from film_locations_in_san_francisco;
select distinct(`Release Year`) from film_locations_in_san_francisco where `Production Company`="Warner Bros. Pictures";
select distinct(Title),`Release Year` from film_locations_in_san_francisco where `Release Year`>"1960";
select distinct(Title), director from film_locations_in_san_francisco where Locations="City Hall"; 
select * from film_locations_in_san_francisco limit 25;
select * from film_locations_in_san_francisco limit 15 offset 10;
select distinct(Title) from film_locations_in_san_francisco limit 50;
select distinct(Title) from film_locations_in_san_francisco where `Release Year`>"1950" limit 50;